### ISSUE TITLE
Question: What are the benefits of this approach vs having standard CMS and use cache

### ISSUE THREAD

**Issue by RosenPetrov** [emmanueltissera/stazorpages#1]
Hello, Emmanuel,

I just read your article on 24days.in (https://24days.in/umbraco-cms/2020/static-website-with-umbraco-heartcore/) and it grabbed my attention. 

I am not familiar with JAMstack and haven't used Umbraco Heartcore yet, so excuse me if my question is dummy. Could you list  some benefits of the stazorpages approach vs using cache in standard Umbraco CMS for example?

Thanks for the good post and the effort you put on this.

**Comment by emmanueltissera** [comment]
Hi @RosenPetrov,

Thank you for reading the article.
A core concept of JAMstack is generating static markup (HTML) files. In order to do this, you would use a headless CMS such as Umbraco Heartcore with a static site generator such as Gatsby or Nuxt. Stazor Pages is an alternative to these static generation tools using .NET 5.

With Umbraco CMS, I would not recommend using Stazor Pages as there is a very mature and well tested caching implementation in the form of NuCache (See this video for more info - https://vimeo.com/183478499#t=1367s). 
Whereas Umbraco CMS could be used to generate a static site, it's more geared towards dynamic websites as you would know 🙂

Hope that clears it up.

Cheers,
Emmanuel
